### ISSUE TITLE
[Feature Request]labels copy

### ISSUE THREAD

**Issue by TinsFox** [actions-cool/create-labels#1]
目前的效果是读取antd的组件，然后生成 `components+组件名` 的label，这种做法在实际应用上好像并不会这么做。
期望的实现效果是
1. 一键copy目标仓库的labels 到自己的仓库
2. 根据模板去一键生成labels
```js
labels:[
   {
     name:"标签名",
     color:"",
     emoji?:""
  },
 {
     name:"标签名",
     color:"",
     emoji?:""
 },
……
]
```

**Comment by xrkffgg** [comment]
support in https://github.com/actions-cool/labels-helper/commit/977cd7a7ea6dfef66f8b6abccc25aa578765ca11
